name: Fineract Demo Build

on:
  push:
    branches:
      - demo3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build with Gradles
        run: ./gradlew --no-daemon -q -x rat -x compileTestJava -x test -x spotlessJavaCheck -x spotlessJava bootJar

      - name: List directory contents
        run: |
          echo "Listing contents of the directory:"
          ls -l ./fineract-provider/build/libs/

      - name: Get Shortened Commit SHA
        id: shortened_sha
        run: |
          FULL_SHA=$GITHUB_SHA
          SHORTENED_SHA=${FULL_SHA:0:8}
          echo "::set-output name=shortened_sha::$SHORTENED_SHA"


      - name: Update known hosts
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan -t rsa ${{ secrets.FITER_DEMO_SERVER_URL }} >> ~/.ssh/known_hosts

      - name: Copy file using SCP
        run: |
          HOST=${{ secrets.FITER_DEMO_SERVER_URL }}
          USER=ubuntu
          SOURCE_FILE=./fineract-provider/build/libs/fineract-provider-0.0.0-${{ steps.shortened_sha.outputs.shortened_sha }}.jar
          DESTINATION_DIR=/home/ubuntu/fineract/
          echo "${{ secrets.FITER_DEMO_SERVER_SSH_KEY }}" > key.pem
          chmod 400 key.pem
          scp -i key.pem -o StrictHostKeyChecking=no $SOURCE_FILE $USER@$HOST:$DESTINATION_DIR


      - name: Build image on server and deploy
        run: ssh -i key.pem -o StrictHostKeyChecking=no -l ubuntu $TEST_SERVER_URL '/home/ubuntu/fineract/build.sh'
        env:
          TEST_SERVER_SSH_KEY: ${{ secrets.FITER_DEMO_SERVER_SSH_KEY }}
          TEST_SERVER_URL: ${{ secrets.FITER_DEMO_SERVER_URL }}
